GridLayout:
    cols: 4 
    rows: 6
    padding: 20
    spacing: 5

    Label: 
        text: 'Result goes here'
        font_size: 32
        
    Button:        
        text: 'CE'
    Button:
        text: 'X'
    Button:
        text: '%'
    Button:        
        text: '÷'
    Button:        
        text: '7'
    Button:        
        text: '8'
    Button:        
        text: '9'
    Button:        
        text: '×'
    Button:        
        text: '4'
    Button:        
        text: '5'
    Button:        
        text: '6'
    Button:        
        text: '-'
    Button:        
        text: '1'
    Button:        
        text: '2'
    Button:        
        text: '3'
    Button:        
        text: '+'
    Button:        
        text: '0'
    Button:        
        text: '.'
    Button:        
        text: '+/-'
    Button:        
        text: '='